New features
bitcoin-sv/ts-sdk pull request #137
Opened 2024-11-07 18:05 UTC by ty-everett

## Description of Changes

- Implement BRC-100 wallet interface
- Add PushDrop token template
- SHIP and SLAP overlay tooling

## Linked Issues / Tickets

SOW C

## Testing Procedure

Describe the tests you've added or any testing steps you've taken.

- [x] I have added new unit tests
- [x] All tests pass locally
- [x] I have tested manually in my local environment

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have updated `CHANGELOG.md` with my changes
- [x] I have run `npm run doc` and `npm run lint` one final time before requesting a review
- [ ] I have run `npm version patch` so that my changes will trigger a new version to be released when they are merged

2024-11-07 18:08 UTC, ty-everett commented
Version 1.2 added to changelog

2024-11-12 19:50 UTC, sirdeggen commented on src/overlay-tools/LookupResolver.ts
> +  // TODO: Specify default trackers.
Once we have the AWS deployment sorted out we can set these to overlay.bsvb.tech I think is the URL. Noting for later.

2024-11-19 09:42 UTC, dorzepowski requested changes

2024-11-19 09:42 UTC, dorzepowski commented on src/wallet/WalletSDK.ts
> +  async createAction(args: { description: DescriptionString5to50Characters, inputs?: Array<{ tx?: BEEF, outpoint: OutpointString, unlockingScript?: HexString, unlockingScriptLength?: PositiveInteger,
I cannot understand this API at all because of the style of typing, the types should be declared separately and named and with some documentation what the given field is representing.

2024-11-19 14:50 UTC, dorzepowski requested changes

2024-11-19 14:50 UTC, dorzepowski commented on src/wallet/Wallet.interface.ts
> +    args: {
args is a commonly used name in typescript for catch all argument which could be misleading for "user" that there aren't any other arguments.

2024-11-19 14:50 UTC, dorzepowski commented on src/wallet/Wallet.interface.ts
> +  createAction: (
again, the argument type should be named and defined separately with the documentation what does that field means. 

I know that there is a description in BRC, but it's very hard to jump between this code and the specification in BRC. 

Beside that BRC is already merged and I have no way to comment there, while here the PR is still opened and I can ask the questions regarding proposed API in reference to given field or type.

2024-11-19 15:00 UTC, chris-4chain commented on src/wallet/substrates/WalletWireTransceiver.ts
> +      paramWriter.writeVarIntNum(-1)
Since the method `wireVarIntNum` is used for negative values, I'm not sure if the implementation for such values (`< 0`) is implemented correctly:

Snippet from: `primitives/utils.ts`:
```ts
static varIntNum (n: number): number[] {
    let buf: number[]
    if (n < 253) {
      buf = [n] // 1 byte
    } else if (n < 0x10000) {
```

Based on that, I can see, positive values (depends on how big they are) are splitted into multiple parts - but not negative ones. 
I wonder - why 🤔

2024-11-19 15:00 UTC, chris-4chain commented on src/wallet/substrates/WalletWireProcessor.ts
> +      let result
unused `result` variable.

2024-11-19 15:00 UTC, chris-4chain commented on src/wallet/substrates/WalletWireProcessor.ts
> +  async transmitToWallet(message: number[]): Promise<number[]> {
It would be nice (for readability sake) to split this long function (basically containing a switch-case) into smaller pieces.

2024-11-19 15:00 UTC, chris-4chain commented on src/wallet/substrates/WalletWireProcessor.ts
> +            const args: any = {}
It would be nice to have such things typed.

2024-11-19 15:00 UTC, chris-4chain commented on src/wallet/substrates/WalletWireProcessor.ts
> +                output.protocol = 'basket insertion'
I would recommend to use a constant here or use an enum.

2024-11-19 15:02 UTC, chris-4chain commented on src/wallet/substrates/XDM.ts
> +          (err as any).code = e.data.code
That was also my concern (below 👇)
https://github.com/bitcoin-sv/ts-sdk/pull/137#discussion_r1848143479

2024-11-19 19:48 UTC, wregulski approved these changes

2024-11-19 19:48 UTC, wregulski commented on src/wallet/WalletSDK.ts
> +        }
I fully agree with Damian, in addition to his comments I would like to point out that it would be much friendlier to read functions/methods such as connectToSubstract if they were divided into smaller parts.

Psuedo code example for current code (didn't remove try catches as Damian suggested):
```ts
private async connectToSubstrate(): Promise<void> {
    const substrates = [this.tryWindowCWI, this.tryXDM, this.tryWalletWire];
    for (const substrate of substrates) {
        const connection = await substrate();
        if (connection) {
            this.substrate = connection;
            return;
        }
    }
    throw new Error('No wallet available over any communication substrate. Install a BSV wallet today!');
}

private async tryWindowCWI(): Promise<Wallet | null> { ... }
private async tryXDM(): Promise<Wallet | null> { ... }
private async tryWalletWire(): Promise<Wallet | null> { ... }
```

2024-11-19 19:48 UTC, wregulski commented on src/wallet/WalletSDK.ts
> +    if (typeof this.substrate === 'object') {
We have a lot of places where we check if substrate is already connected:
signAction, createAction etc.

Consider adding some decorator/wrapper for those repetetive code:
```ts
private async ensureConnected(): Promise<void> {
    if (typeof this.substrate !== 'object') {
        await this.connectToSubstrate();
    }
}
```

2024-11-19 19:48 UTC, wregulski commented on src/wallet/WalletSDK.ts
> +    return await (this.substrate as Wallet).createAction(args, this.originator)
Moreover to @dorzepowski comment do we need await call here?
I think that caller of this method will still be able to await it, as it remains a valid Promise.

2024-11-19 19:48 UTC, wregulski commented on src/wallet/WalletSDK.ts
> +    return await (this.substrate as Wallet).createAction(args, this.originator)
I think it can be omitted in other places also.

2024-11-19 19:49 UTC, wregulski requested changes
General from me - it would be great if we can rethink this repetitive code and probably split it to smaller self-descriptive functions.

2024-11-21 22:24 UTC, BraydenLangley commented on src/wallet/substrates/WalletWireTransceiver.ts
> +    frameWriter.writeUInt8(originator.length)
Updated to be explicit about the support length

2024-11-21 22:26 UTC, BraydenLangley commented on src/wallet/substrates/window.CWI.ts
> +    if (typeof (window as any).CWI !== 'object') {
Thanks, good suggestion

2024-11-21 23:25 UTC, BraydenLangley commented on src/wallet/WalletSDK.ts
> +  async createAction(args: { description: DescriptionString5to50Characters, inputs?: Array<{ tx?: BEEF, outpoint: OutpointString, unlockingScript?: HexString, unlockingScriptLength?: PositiveInteger,
The low level API can be complicated, but for IDE's that don't clearly indicate what parameters need to be provided and this can create a frustrating developer experience if we replace created a typed version that hides away the params. Future code libs can be created that wrap this functionality to make it easier to consume if needed.

Ex. `await createToken(...)`

2024-11-22 18:28 UTC, ty-everett commented on src/overlay-tools/LookupResolver.ts
> +  // TODO: Specify default trackers.
Added some trackers for now, and we can let others add theirs as they come online. Doesn't hurt at all to have more hosts in the list, rather than less :)

2024-11-22 18:30 UTC, ty-everett commented on src/wallet/WalletSDK.ts
> +  async createAction(args: { description: DescriptionString5to50Characters, inputs?: Array<{ tx?: BEEF, outpoint: OutpointString, unlockingScript?: HexString, unlockingScriptLength?: PositiveInteger,
We've got `wallet.interfaces.ts` and we'll start to use things like `CreateActionArgs` where needed.

2024-11-22 18:32 UTC, ty-everett commented on src/wallet/WalletSDK.ts
> +    if (substrate === 'Cicada') substrate = new WalletWireTransceiver(new HTTPWalletWire(originator))
HTTP, BRC-5. This will be covered by future documentation and training programs.

However, people will generally use auto, and things will work.

2024-11-22 18:34 UTC, ty-everett commented on src/wallet/WalletSDK.ts
> +    const checkSub = async (timeout?: number) => {
It's only useful within this context, and it makes use of the `sub` variable which is redeclared at a wider scope.

The function behaves differently when the `sub` variable is rewritten in the wider scope, and it's unwieldy to hoist all of this logic into properties. Because it's only used here, we don't need to bother with it.

2024-11-22 18:38 UTC, ty-everett commented on src/wallet/WalletSDK.ts
> +    if (typeof this.substrate !== 'object') {
Because we cannot put this into the constructor, we must check and initialize if necessary within every function. We cannot rely on consumers to make an `async init()` call when they utilize the wallet, therefore it must be done here, and everywhere.

2024-11-22 18:41 UTC, ty-everett commented on src/wallet/WalletSDK.ts
> +        }
While you make a valid point, there are only three substrates currently. If we were to add more in the future, I think it would be more appropriate to do a refactor at that point — however, for now, I think the code isn't too unreadable, and I think the intended functionality is clear.

2024-11-22 18:43 UTC, ty-everett commented on src/wallet/WalletSDK.ts
> +          await checkSub()
This one will fail without a timeout being reached, given the nature of the specific substrate being checked. HTTP requests, if unsuccessful, will throw immediately, and so will `window.CWI` calls. The one exception to this is the XDM substrate, which will never receive any response if not implemented. Therefore, we need a timeout for checking the XDM, but not for the other two substrates.

2024-11-22 18:44 UTC, ty-everett commented on src/wallet/substrates/XDM.ts
> +    if (typeof window.postMessage !== 'object') {
Yes, good catch, we fixed this one :)

2024-11-22 18:44 UTC, ty-everett commented on src/wallet/substrates/XDM.ts
> +  async invoke(call, args): Promise<any> {
We want to expose it for the purpose of writing our tests, and maybe others want to call it manually somehow.

2024-11-22 18:45 UTC, ty-everett commented on src/wallet/substrates/XDM.ts
> +          (err as any).code = e.data.code
Yes, implemented.

2024-11-22 18:49 UTC, ty-everett commented on src/wallet/substrates/XDM.ts
> +      window.addEventListener('message', async e => {
Great catch, just implemented a fix :)

2024-11-22 19:04 UTC, BraydenLangley commented on src/wallet/substrates/XDM.ts
> +  async invoke(call, args): Promise<any> {
Because the args come from a function that properly implements the wallet interface and are already checked as being correct at that point,  we are simply passing them through here and no additional checks are needed.

With respect to the call param, good catch and I have updated it to be typed as suggested.

2024-11-22 19:08 UTC, ty-everett commented on src/wallet/WalletSDK.ts
> +  async connectToSubstrate() {
There is no auto-selection if the `auto` parameter is not provided. It will associate the selected substrate if necessary.

We are said to be "connected" once we have resolved these discrepencies.

2024-11-22 19:10 UTC, ty-everett commented on src/wallet/Wallet.interface.ts
> +    args: {
In this context, an object that encapsulates all function-specific arguments. The originator is excluded, but it's an object with associated properties for all function arguments. It draws from the same convention, where it's for spreading, except in this context it's an object with named-property arguments rather than an array with values that have (or will be) spread.

2024-11-22 19:12 UTC, ty-everett commented on src/wallet/Wallet.interface.ts
> +  createAction: (
Good point, we've described a function-specific type within `CreateActionArgs`, which we will use in more places.

2024-11-22 19:15 UTC, ty-everett commented on src/wallet/substrates/WalletWireTransceiver.ts
> +      paramWriter.writeVarIntNum(-1)
Because it's only `-1`, and not negative values lower than `-1` (denoting absence of a parameter), there's no real harm here. While it's an interesting quirk of Satoshi's design and `VarInt` in general, we can use it here for a `-1` value without any issues.

2024-11-22 19:22 UTC, ty-everett commented on src/wallet/substrates/WalletWireProcessor.ts
> +            const args: any = {}
We have types in `wallet.interfaces.ts`, and we can try to use `Partial<>` here, and cast to full before making the invocation, once the full set of parameters have been constructed.

2024-11-22 19:29 UTC, ty-everett commented on src/wallet/WalletSDK.ts
> +    return await (this.substrate as Wallet).createAction(args, this.originator)
If the Promise were to reject, we want to have the rejection originate from here, and not from the lower-layer implementation. Maintaining an `await` here ensures that any errors are properly sourced from this function, rather than the pending Promise. It's semantics really, but it also makes stepping through with a debugger easier, to have it await here.

2024-11-22 19:32 UTC, ty-everett commented on src/wallet/substrates/WalletWireTransceiver.ts
> +    frameWriter.write(Utils.toArray(originator, 'utf8'))
Great point, thanks for bringing this to our attention.

We will go through, and make sure that we always make use of the byte length, not the number of character units.

We will update implementation to use byte lengths, and documentations to clarify.

2024-11-22 19:41 UTC, ty-everett commented on src/wallet/substrates/WalletWireTransceiver.ts
> +    frameWriter.write(Utils.toArray(originator, 'utf8'))
We found one case where we weren't setting the length as a number of bytes, but instead we were using a string length:

[a91a105](https://github.com/bitcoin-sv/ts-sdk/pull/137/commits/a91a105c1aebb6aa2cca06b29a79b633b4501d59)

If there are other places, where we inadvertently write the string character length vs. the number of bytes, please let us know and we will fix it.

We've also updated the documentation to reflect number of bytes instead of number of characters.

2024-11-22 20:01 UTC, BraydenLangley commented on src/wallet/WalletSDK.ts
> +  async createAction(args: { description: DescriptionString5to50Characters, inputs?: Array<{ tx?: BEEF, outpoint: OutpointString, unlockingScript?: HexString, unlockingScriptLength?: PositiveInteger,
Used typed params and return values where there was a large number of them in various WalletClient methods.

2024-11-23 15:51 UTC, sirdeggen commented
It's just a monster PR, I'd like to get it in - we can expect to find a bunch more bugs in the coming weeks, but nothing which affects existing users since it'll be limited to within the new classes.

Doing one final review, then let's merge once the checks all pass.

2024-11-25 16:30 UTC, sirdeggen commented on src/overlay-tools/SHIPBroadcaster.ts
> +    this.requireAcknowledgmentFromAllHostsForTopics = requireAcknowledgmentFromAllHostsForTopics ?? 'all'
The default should be set so that ACK from any host for each topic is acceptable. So 

```suggestion
    this.requireAcknowledgmentFromAllHostsForTopics = requireAcknowledgmentFromAllHostsForTopics ?? []
```

2024-11-25 16:31 UTC, sirdeggen commented on src/overlay-tools/SHIPBroadcaster.ts
> +    this.requireAcknowledgmentFromAnyHostForTopics = requireAcknowledgmentFromAnyHostForTopics ?? []
```suggestion
    this.requireAcknowledgmentFromAnyHostForTopics = requireAcknowledgmentFromAnyHostForTopics ?? 'all'
```

2024-11-25 16:34 UTC, sirdeggen requested changes
Let's ensure all tests are passing, once we have that this PR is approved. Further change requests will be made but the PR is unwieldy so we ought to get it in such that more concise PRs can be made which propose improvements to things like the JSDocs on the WalletClient and so on.

2024-11-25 18:14 UTC, sirdeggen approved these changes

2024-11-25 18:21 UTC, merged

2024-11-30 23:06 UTC, sirdeggen commented on src/wallet/WalletSDK.ts
> +        }
Agree this would be neater @wregulski - please PR a refactor to this effect.