[feature] WoC as ChainTracker
bitcoin-sv/ts-sdk pull request #64
Opened 2024-05-13 20:34 UTC by sirdeggen

https://github.com/bitcoin-sv/ts-sdk/issues/61

2024-05-13 21:49 UTC, sirdeggen commented
Added default broadcaster too so that if you just do:

```javascript
await tx.broadcast()
```
it will use WoC.

Acknowledging that ARC is preferable in a production env. WoC can be useful for demos without an api key.

2024-05-14 05:08 UTC, ty-everett requested changes
I'd generally support the addition of these new capabilities, and reluctantly set them as the defaults until options more aligned with SPV and scalability come online.

However, new tests should be introduced that exercise the code, and check any error handling behavior. You can use the `ARC.test.ts` file as a reference for testing the new (and cleverly named) WoCast broadcaster.

Extracting the HTTP client into a util was also a good move.

2024-05-14 05:08 UTC, ty-everett commented on src/transaction/chaintrackers/WoChain.ts
> +        return this
```suggestion
```

2024-05-15 19:58 UTC, sirdeggen commented
@bitcoin-sv/spv-wallet gents can you please take a look at this -- specifically to align with your recent HttpClient abstraction. I think that we should align that and this PR so that there's just the one HttpClient in the library rather than multiple. @dorzepowski asking you specifically in case the team @ doesn't work.

2024-05-15 20:00 UTC, sirdeggen commented
Maybe we should make ARC default @ty-everett - since it doesn't currently require an apiKey.

2024-05-15 20:03 UTC, ty-everett commented
I'd rather Arc be the default, it's more future-proof than WoC and accepts EF. Can we check with TAAL and/or Gorillapool to see what their intentions are with respect to authentication over time?

2024-05-16 13:40 UTC, dorzepowski commented
I will adjust this changes to the approach with HttpClient that is already merged in a new PR.

2024-05-20 13:13 UTC, dorzepowski commented
New PR opened: https://github.com/bitcoin-sv/ts-sdk/pull/67
Therefore this one can be closed

2024-05-20 17:03 UTC, ty-everett commented
Alignment completed by #67 and all merged!

2024-05-20 17:03 UTC, closed without merging